<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<!--
    - Passwortänderung in der Datenbank
    - Wenn user_id in der Tabelle vorhanden wäre, -> update die Geheimzahl
    - Ansonsten füge neue user_id und Geheimzahl in die Datenbank ein 
    - INSERT INTO .....
        ON DUPLICATE KEY UPDATE 
-->
</body>
</html>